### ISSUE TITLE
Сборка падает в самом начале

### ISSUE THREAD

**Issue by klukonin** [intersvyaz/rn-workshop#12]
Официальные инструкции по подготовке окружения не работают на ubuntu 18.04

**При первом запуске выходит следующая ошибка**

$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/klukonin/Documents/DEV/rn-workshop/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug

**При повторном запуске ошибка изменяется на следующую**
$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/klukonin/Documents/DEV/rn-workshop/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class com.android.build.gradle.internal.crash.PluginCrashReporter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug

Сборка падает.

Проверено на open-jdk-8 и oracle-jdk-8

Результат один и тот же.

**Comment by ghost** [comment]
Я бы дал gradle sync отработать ещё раз с хорошим интернетом и перепроверил переменные окружения:
`export | grep "jvm\|JAVA"`

должны быть заявлены
```
JAVA_HOME="/usr/lib/jvm/java-8-oracle"
PATH="..:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin/
```

В крайнем случае - не будет лишним пройтись по инструкции ещё раз.

У некоторых людей наблюдались схожие проблемы - из-за некорректного JAVA_HOME:
https://stackoverflow.com/questions/44416514/react-native-java-lang-exceptionininitializererror
https://stackoverflow.com/questions/55110335/nativescript-helloworld-build-gradle-error
